// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class WindowsEnvironmentOptions {
  WindowsEnvironmentOptions({
    this.userDataPath,
    this.browserExePath,
    this.additionalArguments,
  });

  String? userDataPath;

  String? browserExePath;

  String? additionalArguments;

  List<Object?> _toList() {
    return <Object?>[userDataPath, browserExePath, additionalArguments];
  }

  Object encode() {
    return _toList();
  }

  static WindowsEnvironmentOptions decode(Object result) {
    result as List<Object?>;
    return WindowsEnvironmentOptions(
      userDataPath: result[0] as String?,
      browserExePath: result[1] as String?,
      additionalArguments: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WindowsEnvironmentOptions ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(userDataPath, other.userDataPath) &&
        _deepEquals(browserExePath, other.browserExePath) &&
        _deepEquals(additionalArguments, other.additionalArguments);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WindowsEnvironmentOptions(userDataPath: $userDataPath, browserExePath: $browserExePath, additionalArguments: $additionalArguments)';
  }
}

class WindowsCreateWebViewResult {
  WindowsCreateWebViewResult({required this.textureId});

  int textureId;

  List<Object?> _toList() {
    return <Object?>[textureId];
  }

  Object encode() {
    return _toList();
  }

  static WindowsCreateWebViewResult decode(Object result) {
    result as List<Object?>;
    return WindowsCreateWebViewResult(textureId: result[0]! as int);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WindowsCreateWebViewResult ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(textureId, other.textureId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WindowsCreateWebViewResult(textureId: $textureId)';
  }
}

class WindowsCookieData {
  WindowsCookieData({
    required this.name,
    required this.value,
    required this.domain,
    required this.path,
    this.expires,
    this.isHttpOnly,
    this.isSecure,
    this.sameSite,
    this.isSession,
  });

  String name;

  String value;

  String domain;

  String path;

  double? expires;

  bool? isHttpOnly;

  bool? isSecure;

  int? sameSite;

  bool? isSession;

  List<Object?> _toList() {
    return <Object?>[
      name,
      value,
      domain,
      path,
      expires,
      isHttpOnly,
      isSecure,
      sameSite,
      isSession,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WindowsCookieData decode(Object result) {
    result as List<Object?>;
    return WindowsCookieData(
      name: result[0]! as String,
      value: result[1]! as String,
      domain: result[2]! as String,
      path: result[3]! as String,
      expires: result[4] as double?,
      isHttpOnly: result[5] as bool?,
      isSecure: result[6] as bool?,
      sameSite: result[7] as int?,
      isSession: result[8] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WindowsCookieData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(value, other.value) &&
        _deepEquals(domain, other.domain) &&
        _deepEquals(path, other.path) &&
        _deepEquals(expires, other.expires) &&
        _deepEquals(isHttpOnly, other.isHttpOnly) &&
        _deepEquals(isSecure, other.isSecure) &&
        _deepEquals(sameSite, other.sameSite) &&
        _deepEquals(isSession, other.isSession);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WindowsCookieData(name: $name, value: $value, domain: $domain, path: $path, expires: $expires, isHttpOnly: $isHttpOnly, isSecure: $isSecure, sameSite: $sameSite, isSession: $isSession)';
  }
}

class WindowsPointData {
  WindowsPointData({required this.x, required this.y});

  double x;

  double y;

  List<Object?> _toList() {
    return <Object?>[x, y];
  }

  Object encode() {
    return _toList();
  }

  static WindowsPointData decode(Object result) {
    result as List<Object?>;
    return WindowsPointData(x: result[0]! as double, y: result[1]! as double);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WindowsPointData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(x, other.x) && _deepEquals(y, other.y);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WindowsPointData(x: $x, y: $y)';
  }
}

class WindowsSizeData {
  WindowsSizeData({
    required this.width,
    required this.height,
    required this.scaleFactor,
  });

  double width;

  double height;

  double scaleFactor;

  List<Object?> _toList() {
    return <Object?>[width, height, scaleFactor];
  }

  Object encode() {
    return _toList();
  }

  static WindowsSizeData decode(Object result) {
    result as List<Object?>;
    return WindowsSizeData(
      width: result[0]! as double,
      height: result[1]! as double,
      scaleFactor: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WindowsSizeData || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(scaleFactor, other.scaleFactor);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WindowsSizeData(width: $width, height: $height, scaleFactor: $scaleFactor)';
  }
}

class WindowsPointerUpdateData {
  WindowsPointerUpdateData({
    required this.pointer,
    required this.event,
    required this.x,
    required this.y,
    required this.size,
    required this.pressure,
  });

  int pointer;

  int event;

  double x;

  double y;

  double size;

  double pressure;

  List<Object?> _toList() {
    return <Object?>[pointer, event, x, y, size, pressure];
  }

  Object encode() {
    return _toList();
  }

  static WindowsPointerUpdateData decode(Object result) {
    result as List<Object?>;
    return WindowsPointerUpdateData(
      pointer: result[0]! as int,
      event: result[1]! as int,
      x: result[2]! as double,
      y: result[3]! as double,
      size: result[4]! as double,
      pressure: result[5]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WindowsPointerUpdateData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pointer, other.pointer) &&
        _deepEquals(event, other.event) &&
        _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(size, other.size) &&
        _deepEquals(pressure, other.pressure);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WindowsPointerUpdateData(pointer: $pointer, event: $event, x: $x, y: $y, size: $size, pressure: $pressure)';
  }
}

class WindowsPointerButtonData {
  WindowsPointerButtonData({required this.button, required this.isDown});

  int button;

  bool isDown;

  List<Object?> _toList() {
    return <Object?>[button, isDown];
  }

  Object encode() {
    return _toList();
  }

  static WindowsPointerButtonData decode(Object result) {
    result as List<Object?>;
    return WindowsPointerButtonData(
      button: result[0]! as int,
      isDown: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WindowsPointerButtonData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(button, other.button) &&
        _deepEquals(isDown, other.isDown);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WindowsPointerButtonData(button: $button, isDown: $isDown)';
  }
}

class WindowsVirtualHostMappingData {
  WindowsVirtualHostMappingData({
    required this.hostName,
    required this.path,
    required this.accessKind,
  });

  String hostName;

  String path;

  int accessKind;

  List<Object?> _toList() {
    return <Object?>[hostName, path, accessKind];
  }

  Object encode() {
    return _toList();
  }

  static WindowsVirtualHostMappingData decode(Object result) {
    result as List<Object?>;
    return WindowsVirtualHostMappingData(
      hostName: result[0]! as String,
      path: result[1]! as String,
      accessKind: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WindowsVirtualHostMappingData ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hostName, other.hostName) &&
        _deepEquals(path, other.path) &&
        _deepEquals(accessKind, other.accessKind);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WindowsVirtualHostMappingData(hostName: $hostName, path: $path, accessKind: $accessKind)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is WindowsEnvironmentOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is WindowsCreateWebViewResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is WindowsCookieData) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is WindowsPointData) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is WindowsSizeData) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is WindowsPointerUpdateData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is WindowsPointerButtonData) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is WindowsVirtualHostMappingData) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return WindowsEnvironmentOptions.decode(readValue(buffer)!);
      case 130:
        return WindowsCreateWebViewResult.decode(readValue(buffer)!);
      case 131:
        return WindowsCookieData.decode(readValue(buffer)!);
      case 132:
        return WindowsPointData.decode(readValue(buffer)!);
      case 133:
        return WindowsSizeData.decode(readValue(buffer)!);
      case 134:
        return WindowsPointerUpdateData.decode(readValue(buffer)!);
      case 135:
        return WindowsPointerButtonData.decode(readValue(buffer)!);
      case 136:
        return WindowsVirtualHostMappingData.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class WindowsWebViewHostApi {
  /// Constructor for [WindowsWebViewHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WindowsWebViewHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initializeEnvironment(WindowsEnvironmentOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.initializeEnvironment$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[options],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String?> getWebViewVersion() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.getWebViewVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<WindowsCreateWebViewResult> createWebView() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.createWebView$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WindowsCreateWebViewResult;
  }

  Future<void> disposeWebView(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.disposeWebView$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> loadUrl(int textureId, String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.loadUrl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> loadStringContent(int textureId, String content) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.loadStringContent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, content],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> reload(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.reload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stop(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> goBack(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.goBack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> goForward(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.goForward$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String?> addScriptToExecuteOnDocumentCreated(
    int textureId,
    String script,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.addScriptToExecuteOnDocumentCreated$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, script],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<void> removeScriptToExecuteOnDocumentCreated(
    int textureId,
    String scriptId,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.removeScriptToExecuteOnDocumentCreated$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, scriptId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String> executeScript(int textureId, String script) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.executeScript$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, script],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> postWebMessage(int textureId, String message) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.postWebMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, message],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setUserAgent(int textureId, String userAgent) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setUserAgent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, userAgent],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<bool> clearCookies(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.clearCookies$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> setCookie(int textureId, WindowsCookieData cookie) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setCookie$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, cookie],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<List<WindowsCookieData?>> getCookies(int textureId, String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.getCookies$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<WindowsCookieData?>();
  }

  Future<void> deleteCookie(int textureId, WindowsCookieData cookie) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.deleteCookie$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, cookie],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> deleteCookiesWithNameAndUrl(
    int textureId,
    String name,
    String url,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.deleteCookiesWithNameAndUrl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, name, url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> deleteCookiesWithNameDomainAndPath(
    int textureId,
    String name,
    String domain,
    String path,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.deleteCookiesWithNameDomainAndPath$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, name, domain, path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> clearCache(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.clearCache$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setCacheDisabled(int textureId, bool disabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setCacheDisabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, disabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> openDevTools(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.openDevTools$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setBackgroundColor(int textureId, int color) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setBackgroundColor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, color],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setZoomFactor(int textureId, double zoomFactor) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setZoomFactor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, zoomFactor],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setPopupWindowPolicy(int textureId, int policy) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setPopupWindowPolicy$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, policy],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> suspend(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.suspend$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> resume(int textureId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.resume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setVirtualHostNameMapping(
    int textureId,
    WindowsVirtualHostMappingData mapping,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setVirtualHostNameMapping$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, mapping],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> clearVirtualHostNameMapping(
    int textureId,
    String hostName,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.clearVirtualHostNameMapping$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, hostName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setFpsLimit(int textureId, int maxFps) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setFpsLimit$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, maxFps],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setPointerUpdate(
    int textureId,
    WindowsPointerUpdateData update,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setPointerUpdate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, update],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setCursorPos(int textureId, WindowsPointData position) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setCursorPos$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, position],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setPointerButton(
    int textureId,
    WindowsPointerButtonData button,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setPointerButton$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, button],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setScrollDelta(int textureId, WindowsPointData delta) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setScrollDelta$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, delta],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setSize(int textureId, WindowsSizeData size) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.webview_all_windows.WindowsWebViewHostApi.setSize$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[textureId, size],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}
