name: webview_all_ohos
description: OpenHarmony implementation of the webview_all federated WebView plugin.
repository: https://github.com/moluopro/webview_all
homepage: https://github.com/moluopro/webview_all
issue_tracker: https://github.com/moluopro/webview_all/issues
version: 1.1.1

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

flutter:
  plugin:
    implements: webview_all
    platforms:
      ohos:
        package: com.abandoft.webview_all_ohos
        pluginClass: WebViewFlutterPlugin
        dartPluginClass: OhosWebViewPlatform

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_platform_interface: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
